# Generated by Django 2.0.6 on 2018-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Movie Genree')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField()),
                ('director', models.CharField(max_length=255)),
                ('imdb_score', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('genre', models.ManyToManyField(to='api.MovieGenres')),
            ],
        ),
    ]
