# Generated by Django 2.0.6 on 2018-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecords',
            name='popularity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
