# Generated by Django 2.0.6 on 2018-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180621_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecords',
            name='popularity',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
